### ISSUE TITLE
Implement Quick sort

### ISSUE THREAD

**Issue by narnat** [Jovidon/Algorito#5]
Implement quick sort in C++ and/or any other language

- [x] Implement Quick sort
- [x] Add tests

**Comment by TawfikYasser** [comment]
Hi @narnat I want to add the quick sort algorithm in C++

**Comment by narnat** [comment]
> Hi @narnat I want to add the quick sort algorithm in C++

Hello @TawfikYasser, sure. Feel free to make a PR

**Comment by TawfikYasser** [comment]
Thanks @narnat

**Comment by Jovidon** [comment]
Hello @TawfikYasser. Thank you for your contribution.
Contributions are welcome!

**Comment by TawfikYasser** [comment]
It’s a great chance for me. :) @Jovidon

**Comment by narnat** [comment]
> Thanks @narnat

@TawfikYasser you are welcome!
